#
#   Copyright (c) 2015-2016 Philipp Paulweber
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 https://github.com/ppaulweber/libpass
#
#   This file is part of libpass.
#
#   libpass is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   libpass is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with libpass. If not, see <http://www.gnu.org/licenses/>.
#

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
  allow_failures:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: gcc

install:
  - |
    echo ${TRAVIS_OS_NAME}
    make  --version
    cmake --version
    ${CC} --version
    ${CXX} --version


script:
  - |
    make debug-all
    make debug-test
    make debug-benchmark
    make sanitize-all
    make sanitize-test
    make sanitize-benchmark
    make release-all
    make release-test
    make release-benchmark
